coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "**/*_test.go"
  - "**/test/**"
  - "**/tests/**"
  - "**/mock/**"
  - "**/mocks/**"
  - "**/*.pb.go"
  - "**/gen/**"
  - "**/cmd/**"