version: "2"

run:
  timeout: 5m
  tests: true

# v2: formatters are separate from linters
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(example.com)
      custom-order: true
    goimports:
      local-prefixes:
        - example.com

linters:
  enable:
    - bodyclose
    - errcheck
    - gochecknoinits
    - goconst
    - cyclop            # replaces deprecated gocyclo
    - gosec
    - govet             # vet checks (type-related, etc.)
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck       # v2: use this instead of gosimple/stylecheck
    - unconvert
    - unparam
    - unused            # keep explicit unused checks
    - whitespace
    - copyloopvar       # replaces deprecated exportloopref

  settings:
    lll:
      line-length: 140
    misspell:
      locale: US
    goconst:
      min-len: 2
      min-occurrences: 3
    cyclop:
      max-complexity: 15
    funlen:
      lines: 100
      statements: 50
    govet:
      enable:
        - fieldalignment

  # v2: exclusions live here (not under `issues`)
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - goconst
          - funlen
      - path: cmd/
        linters:
          - gochecknoinits
