version: "2"

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(example.com)
      custom-order: true
    goimports:
      local-prefixes:
        - example.com

linters:
  enable:
    - bodyclose
    - errcheck
    - gochecknoinits
    - goconst
    - cyclop
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - copyloopvar

  settings:
    lll:
      line-length: 140
    misspell:
      locale: US
    goconst:
      min-len: 2
      min-occurrences: 3
    cyclop:
      max-complexity: 15
    funlen:
      lines: 100
      statements: 50
    govet:
      enable:
        - fieldalignment

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - goconst
          - funlen
      - path: ^cmd/
        linters:
          - gochecknoinits
