version: "2"

run:
  timeout: 5m
  tests: true

linters-settings:
  # Prefer gci for import grouping (actively maintained)
  gci:
    sections:
      - standard
      - default
      - prefix(example.com)
    skip-generated: true

  goimports:
    local-prefixes: example.com

  # Use cyclop instead of deprecated gocyclo
  cyclop:
    max-complexity: 15
    package-average: false
    skip-tests: true

  lll:
    line-length: 140

  misspell:
    locale: US

  goconst:
    min-len: 2
    min-occurrences: 3

  funlen:
    lines: 100
    statements: 50

  # (Optional) keep useful vet checks explicitly enabled
  govet:
    enable:
      - fieldalignment

linters:
  enable:
    - bodyclose
    - errcheck
    - gci
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - cyclop
    - copyloopvar   # replacement for exportloopref on modern Go

  # Remove deprecated/duplicate toggles
  disable:
  # (empty on purpose)
  # If you need to turn something off, add it here—but do NOT
  # duplicate anything already enabled above.

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - goconst
        - funlen
    - path: cmd/
      linters:
        - gochecknoinits
