version: "2"

run:
  timeout: 5m
  tests: true

# v2: formatters are separate from linters
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(example.com)
      custom-order: true
    goimports:
      local-prefixes:
        - example.com

linters:
  enable:
    - bodyclose
    - errcheck
    - gochecknoinits
    - goconst
    - cyclop            # replaces deprecated gocyclo
    - gosec
    - govet             # vet/type-related checks
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck       # covers gosimple/stylecheck in v2
    - unconvert
    - unparam
    - unused
    - whitespace
    - copyloopvar       # replaces deprecated exportloopref

  settings:
    lll:
      line-length: 140
    misspell:
      locale: US
    goconst:
      min-len: 2
      min-occurrences: 3
    cyclop:
      max-complexity: 15
    funlen:
      lines: 100
      statements: 50
    govet:
      enable:
        - fieldalignment

  # v2: use path-based exclusions here (not run.skip-dirs / issues.*)
  exclusions:
    rules:
      # Relax tests a bit
      - path: _test\.go
        linters:
          - errcheck
          - goconst
          - funlen

      # Don't enforce init rule in CLI entrypoints
      - path: ^cmd/
        linters:
          - gochecknoinits

      # Generated/OpenAPI code often can't be type-checked in CI before generation.
      # Keep formatters and heavy analyzers off these paths.
      - path: ^gen/
        linters:
          - gci
          - gofmt
          - goimports
          - govet
          - staticcheck
          - ineffassign
          - unused
          - unparam
          - unconvert
          - bodyclose
          - errcheck
          - gosec
          - lll
          - nakedret
          - whitespace
          - cyclop
          - goconst
