version: "2"

run:
  timeout: 5m
  tests: true

# Formatters are separate from linters in v2
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(example.com)
      custom-order: true
    goimports:
      local-prefixes:
        - example.com

linters:
  enable:
    - bodyclose
    - errcheck
    - gochecknoinits
    - goconst
    - cyclop          # use cyclop (gocyclo is deprecated)
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - copyloopvar     # replacement for exportloopref

  settings:
    lll:
      line-length: 140
    misspell:
      locale: US
    goconst:
      min-len: 2
      min-occurrences: 3
    cyclop:
      max-complexity: 15      # keep only supported keys
    funlen:
      lines: 100
      statements: 50
    govet:
      enable:
        - fieldalignment

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - goconst
        - funlen
    - path: cmd/
      linters:
        - gochecknoinits
