version: "2"

run:
  timeout: 5m
  tests: true

# Code formatters (v2 config separates these from linters)
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(example.com)
      custom-order: true
    goimports:
      local-prefixes:
        - example.com

linters:
  enable:
    - bodyclose
    - errcheck
    - gochecknoinits
    - goconst
    - cyclop          # replacement for deprecated gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - copyloopvar     # replacement for deprecated exportloopref

  settings:
    lll:
      line-length: 140
    misspell:
      locale: US
    goconst:
      min-len: 2
      min-occurrences: 3
    cyclop:
      max-complexity: 15
      package-average: false
      skip-tests: true
    funlen:
      lines: 100
      statements: 50
    govet:
      enable:
        - fieldalignment

  # v2-style exclusions live under linters.exclusions
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - goconst
          - funlen
      - path: cmd/
        linters:
          - gochecknoinits
