openapi: 3.0.0
info:
  title: Template
  description: A API for managing Template posting and application.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /auth/signup:
    post:
      summary: signup
      responses:
        '204':
          description: signup

  /auth/login:
    post:
      summary: login
      responses:
        '204':
          description: login