# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - docker-compose up -d db
      - docker-compose up app
  install:
    cmds:
      - docker-compose up --build -d db
      - docker-compose up --build app
  bash:
    cmds:
      - docker-compose exec app bash
  test:
    cmds:
      - JWT_SECRET_KEY="test-secret-key" go test -parallel 4 ./tests/...
  coverage:
    cmds:
      - JWT_SECRET_KEY="test-secret-key" go test -parallel 4 -covermode=atomic -coverpkg="$(go list ./internal/...)"  ./...
  lint:
    cmds:
      - docker-compose run --rm lint
  down:
    cmds:
      - docker-compose down
  destroy:
    cmds:
      - docker-compose down --rmi all --volumes --remove-orphans
  db:
    cmds:
      - docker-compose exec db psql -U "user" "template"